apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngixn-deployment-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      name: nginx-pod-test
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx-test-container
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
spec:
  selector:
    app: nginx-test
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80